%% Read practice data
featuredata = {'Sample_title', 'Benign 2', 'Benign 3', 'Benign 6', 'Benign 7', 'Benign 9', 'Adeno 1', 'Adeno 2', 'Adeno 3', 'Adeno 4', 'Adeno 7', 'Adeno 8', 'Adeno 9', 'SCLC 1', 'SCLC 4', 'SCLC 6', 'SCLC 7', 'SCLC 8', 'Squamous 2', 'Squamous 4', 'Squamous 5', 'Squamous 6', 'Squamous 7', 'Squamous 8', 'Squamous 9'; ...
                'diagnosis', 'Benign', 'Benign', 'Benign', 'Benign', 'Benign', 'Adeno', 'Adeno', 'Adeno', 'Adeno', 'Adeno', 'Adeno', 'Adeno', 'SCLC', 'SCLC', 'SCLC', 'SCLC', 'SCLC', 'Squamous', 'Squamous', 'Squamous', 'Squamous', 'Squamous', 'Squamous', 'Squamous'; ...
                'miR_expression', 2.6088, 3.1043, 1.2016, 2.4594, 1.5849, 3.8176, 5.5235, 2.4594, 5.3854, 5.2288, 4.0959, 4.8579, 3.8875, 2.4854, 4.6028, 3.6088, 2.6780, 1.7655, 3.0874, 3.0703, 4.0703, 3.0531, 4.0531, 4.0179; ...
                'smoking_status', 'former', 'former', 'current', 'former', 'never', 'current', 'current', 'never', 'former', 'never', 'never', 'current', 'former', 'current', 'never', 'former', 'former', 'former', 'never', 'current', 'current', 'current', 'former', 'current'};

%% Prepare inputs
col_start = 2; % Column start of numeric data

% Numeric expression data
data = cell2mat(featuredata(3,col_start:end)); 

% Grouping data by diagnosis
groups = featuredata(2,col_start:end); 

% Grouping data by smoking status
smoking_groups = featuredata(4, col_start:end); 

%% Prepare optional inputs
% Sorting order of diagnoses
sortOrder = {'Adeno', 'Benign', 'SCLC','Squamous'}; 

% Colour vectors (nx3)
colors = [0.615686274509804,0.678431372549020,0.435294117647059;...
         0.921568627450980,0.396078431372549,0.203921568627451;...
         0.60,0.80,1;...
         0.996078431372549,0.776470588235294,0.121568627450980];

%% Generate jitterplot
% Generate jitterplot without 'colorgrp', defaults to colouring based on
% 'groups'
jitterplot(data, groups, ...
    'PlotTitle',{'microRNA expression'}, ...
    'xlabel', 'Diagnosis', ...
    'ylabel', 'microRNA Expression value', ...
    'colorgrp', [],...
    'jitter', 0.6, ...
    'colors', colors, ...
    'sortOrder',sortOrder, ...
    'showLegend', true, ...
    'showMedianValues', true);

% Empty sortOrder - displays data in order that it is presented
jitterplot(data, groups, ...
    'PlotTitle',{'microRNA expression'}, ...
    'xlabel', 'Diagnosis', ...
    'ylabel', 'microRNA Expression value', ...
    'colorgrp', [],...
    'jitter', 0.6, ...
    'colors', colors, ...
    'sortOrder',[], ...
    'showLegend', true, ...
    'showMedianValues', true);

% Colorgrp - assign datapoint colors based on a different grouping
% variable (ex., smoking status)
jitterplot(data, groups, ...
    'PlotTitle',{'microRNA expression'}, ...
    'xlabel', 'Diagnosis', ...
    'ylabel', 'microRNA Expression value', ...
    'colorgrp', smoking_groups,...
    'jitter', 0.6, ...
    'colors', colors, ...
    'sortOrder',sortOrder, ...
    'showLegend', true, ...
    'showMedianValues', true);

% No colors vector indicated - defaults to blue
jitterplot(data, groups, ...
    'PlotTitle',{'microRNA expression'}, ...
    'xlabel', 'Diagnosis', ...
    'ylabel', 'microRNA Expression value', ...
    'colorgrp', [],...
    'jitter', 0.6, ...
    'colors', [], ...
    'sortOrder',sortOrder, ...
    'showLegend', true, ...
    'showMedianValues', true);



